### ISSUE TITLE
helptag Conflict 

### ISSUE THREAD

**Issue by tsuyoshicho** [kyoh86/vim-editerm#16]
https://github.com/kyoh86/vim-editerm/blob/46977664cc5bc5f71d3964c63ad6f94c0b87684a/doc/vim-editerm.txt#L1

https://github.com/kyoh86/vim-editerm/blob/46977664cc5bc5f71d3964c63ad6f94c0b87684a/doc/vim-editerm.txt#L24-L26

Conflict `*vim-editerm*`

```
repo> vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
(exit 1)
```

(And I know. Basically, vim helptag do not contain in repository.)

**Comment by kyoh86** [comment]
thanks, I'll fix it now.
