### ISSUE TITLE
error: `Not an editor command: scriptversion 3`

### ISSUE THREAD

**Issue by jajaperson** [kyoh86/vim-editerm#21]
When launching vim with this plugin, I get the following error: 
```
E492: Not an editor command: scriptversion 3
```

![image](https://user-images.githubusercontent.com/25611007/149501503-b0260ae6-9497-4a15-9706-95c42d71aa36.png)

I am using SpaceVim on a Mac with Alacritty.

**Comment by kyoh86** [comment]
I won't support SpaceVim.
